name: Build and Push Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Artifact
      run: |
        mkdir -p artifacts
        cp simple.json artifacts/

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: json-artifact
        path: artifacts/simple.json
